[package]
name = "twentyfive-stars-server"
version = "0.1.0"
authors = ["Blaine Bublitz <blaine.bublitz@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
diesel = { version = "=1.4.3", features = ["postgres", "chrono", "uuidv07"] }
dotenv = "0.9.0"
juniper = { version = "=0.14.2", features = ["uuid"] }
juniper_iron = "0.6.1"
iron = "0.6.1"
mount = "0.4.0"
logger = "0.4.0"
env_logger = "0.7.1"
chrono = "0.4.1"
uuid = { version = "=0.7.4", features = ["serde", "v4"] }
base64 = "0.11.0"
diesel-derive-newtype = "0.1.2"
