[package]
name = "twentyfive-stars-server"
version = "0.1.0"
authors = ["Blaine Bublitz <blaine.bublitz@gmail.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
async-graphql = "1.14.0"
async-graphql-tide = "1.14.0"
chrono = "0.4.11"
dotenv = "0.15.0"
env_logger = "0.7.1"
futures = "0.3.5"
smol = "0.1.0"
sqlx = { path = "../../sqlx", features = ["postgres", "chrono", "uuid", "offline"] }
tide = "0.8.1"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
